name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
        
      - name: Build Vite project
        run: pnpm run build
        
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm run test
        env:
          CI: true

      # - name: Deploy to GCP
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY}}
      #   run: |
      #     echo $GOOGLE_APPLICATION_CREDENTIALS > key.json
      #     gcloud auth activate-service-account --key-file=key.json
      #     gcloud app deploy --quiet